export interface Seed {
  id: string;
  img: string;
  name: string;
  germination_rate: string;
  seed_count: string;
  origin: string;
  season: string;
  url: string;
  description: string;
  planting_depth: string;
  spacing: string;
  sun_exposure: string;
  watering: string;
  days_to_germination: string;
  days_to_harvest: string;
  height: string;
  soil_type: string;
  companion_plants: string[];
}

export const seeds: Seed[] = [
  {
    id: "001",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269308/19ab542e3b.jpg",
    name: "Semente de Girassol",
    germination_rate: "90%",
    seed_count: "30",
    origin: "Brasil",
    season: "Primavera/Verão",
    url: "https://example.com/girassol-ornamental",
    description:
      "O girassol é uma planta anual conhecida por suas flores grandes e vistosas que seguem o movimento do sol. Além de seu valor ornamental, suas sementes são ricas em óleos e nutrientes, sendo utilizadas tanto para consumo humano quanto para produção de óleo vegetal.",
    planting_depth: "2-3 cm",
    spacing: "30-45 cm",
    sun_exposure: "Sol pleno (6-8 horas diárias)",
    watering: "Regular, mantendo o solo úmido mas não encharcado",
    days_to_germination: "7-10 dias",
    days_to_harvest: "80-120 dias",
    height: "1.5-3 metros",
    soil_type: "Bem drenado, rico em matéria orgânica",
    companion_plants: ["Pepino", "Milho", "Feijão"],
  },
  {
    id: "002",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269309/tomate-cereja.jpg",
    name: "Tomate Cereja",
    germination_rate: "85%",
    seed_count: "25",
    origin: "México",
    season: "Primavera/Verão",
    url: "https://example.com/tomate-cereja",
    description:
      "O tomate cereja é uma variedade pequena e doce, ideal para cultivo em vasos e jardins. Produz frutos vermelhos brilhantes em cachos, sendo muito apreciado em saladas e como petisco.",
    planting_depth: "0.5-1 cm",
    spacing: "40-60 cm",
    sun_exposure: "Sol pleno (6-8 horas diárias)",
    watering: "Regular, mantendo o solo uniformemente úmido",
    days_to_germination: "5-10 dias",
    days_to_harvest: "60-70 dias",
    height: "1-1.8 metros",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Manjericão", "Cebolinha", "Alface"],
  },
  {
    id: "003",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269310/alface-crespa.jpg",
    name: "Alface Crespa",
    germination_rate: "95%",
    seed_count: "100",
    origin: "Mediterrâneo",
    season: "Ano todo",
    url: "https://example.com/alface-crespa",
    description:
      "A alface crespa é uma hortaliça folhosa de crescimento rápido, com folhas onduladas e textura crocante. É rica em vitaminas e minerais, sendo um componente básico em saladas.",
    planting_depth: "0.5 cm",
    spacing: "25-30 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Frequente, mantendo o solo sempre úmido",
    days_to_germination: "7-10 dias",
    days_to_harvest: "45-55 dias",
    height: "20-30 cm",
    soil_type: "Fértil, rico em matéria orgânica",
    companion_plants: ["Cenoura", "Rabanete", "Cebola"],
  },
  {
    id: "004",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269311/cenoura.jpg",
    name: "Cenoura",
    germination_rate: "80%",
    seed_count: "200",
    origin: "Ásia",
    season: "Outono/Inverno",
    url: "https://example.com/cenoura",
    description:
      "A cenoura é uma raiz tuberosa alaranjada rica em betacaroteno. Versátil na culinária, pode ser consumida crua ou cozida, sendo apreciada pelo sabor adocicado e valor nutricional.",
    planting_depth: "0.5-1 cm",
    spacing: "5-8 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, evitando encharcamento",
    days_to_germination: "10-15 dias",
    days_to_harvest: "70-80 dias",
    height: "30-40 cm (folhagem)",
    soil_type: "Arenoso, profundo, sem pedras",
    companion_plants: ["Alface", "Ervilha", "Alho-poró"],
  },
  {
    id: "005",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269312/manjericao.jpg",
    name: "Manjericão",
    germination_rate: "85%",
    seed_count: "150",
    origin: "Índia",
    season: "Primavera/Verão",
    url: "https://example.com/manjericao",
    description:
      "O manjericão é uma erva aromática com folhas verdes brilhantes e aroma característico. Muito utilizado na culinária mediterrânea, especialmente em pratos italianos, molhos e pestos.",
    planting_depth: "0.5 cm",
    spacing: "20-25 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, deixando secar entre regas",
    days_to_germination: "5-10 dias",
    days_to_harvest: "60-90 dias",
    height: "30-60 cm",
    soil_type: "Bem drenado, rico em nutrientes",
    companion_plants: ["Tomate", "Pimentão", "Orégano"],
  },
  {
    id: "006",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269313/rucula.jpg",
    name: "Rúcula",
    germination_rate: "90%",
    seed_count: "120",
    origin: "Mediterrâneo",
    season: "Outono/Inverno",
    url: "https://example.com/rucula",
    description:
      "A rúcula é uma hortaliça de folhas verdes escuras com sabor picante e levemente amargo. Rica em vitaminas e minerais, é muito apreciada em saladas e como complemento em diversos pratos.",
    planting_depth: "0.5 cm",
    spacing: "15-20 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "3-7 dias",
    days_to_harvest: "30-40 dias",
    height: "15-30 cm",
    soil_type: "Fértil, bem drenado",
    companion_plants: ["Alface", "Tomate", "Morango"],
  },
  {
    id: "007",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269314/coentro.jpg",
    name: "Coentro",
    germination_rate: "75%",
    seed_count: "100",
    origin: "Oriente Médio",
    season: "Ano todo",
    url: "https://example.com/coentro",
    description:
      "O coentro é uma erva aromática de folhas recortadas e aroma intenso. Muito utilizado na culinária asiática, latina e nordestina brasileira, suas folhas e sementes (coentro seco) são aproveitadas em diversos pratos.",
    planting_depth: "1 cm",
    spacing: "10-15 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "45-60 dias",
    height: "30-50 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Cebolinha", "Alho", "Ervilha"],
  },
  {
    id: "008",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269315/pimentao.jpg",
    name: "Pimentão",
    germination_rate: "80%",
    seed_count: "30",
    origin: "América Central",
    season: "Primavera/Verão",
    url: "https://example.com/pimentao",
    description:
      "O pimentão é um fruto da família das solanáceas, disponível em diversas cores (verde, vermelho, amarelo). Possui sabor adocicado e é muito versátil na culinária, podendo ser consumido cru ou cozido.",
    planting_depth: "0.5-1 cm",
    spacing: "40-50 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, evitando encharcamento",
    days_to_germination: "10-15 dias",
    days_to_harvest: "70-90 dias",
    height: "60-90 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Manjericão", "Cebolinha", "Cenoura"],
  },
  {
    id: "009",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269316/abobrinha.jpg",
    name: "Abobrinha",
    germination_rate: "85%",
    seed_count: "20",
    origin: "América Central",
    season: "Primavera/Verão",
    url: "https://example.com/abobrinha",
    description:
      "A abobrinha é um fruto alongado de casca verde clara e polpa branca. De sabor suave, é muito utilizada em refogados, grelhados, recheada ou em massas como pães e bolos.",
    planting_depth: "2-3 cm",
    spacing: "60-90 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-10 dias",
    days_to_harvest: "45-55 dias",
    height: "60-90 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Milho", "Feijão", "Manjericão"],
  },
  {
    id: "010",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269317/beterraba.jpg",
    name: "Beterraba",
    germination_rate: "75%",
    seed_count: "100",
    origin: "Europa",
    season: "Outono/Inverno",
    url: "https://example.com/beterraba",
    description:
      "A beterraba é uma raiz tuberosa de cor vermelho-púrpura intensa, com sabor adocicado e terroso. Rica em antioxidantes e nutrientes, pode ser consumida crua em saladas ou cozida em diversos pratos.",
    planting_depth: "1-2 cm",
    spacing: "10-15 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "55-70 dias",
    height: "30-45 cm (folhagem)",
    soil_type: "Solto, profundo, bem drenado",
    companion_plants: ["Cebola", "Alface", "Repolho"],
  },
  {
    id: "011",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269318/pepino.jpg",
    name: "Pepino",
    germination_rate: "90%",
    seed_count: "25",
    origin: "Índia",
    season: "Primavera/Verão",
    url: "https://example.com/pepino",
    description:
      "O pepino é um fruto alongado de casca verde e polpa clara, crocante e refrescante. Muito utilizado em saladas, conservas e como petisco, possui alto teor de água e baixo valor calórico.",
    planting_depth: "1-2 cm",
    spacing: "50-60 cm",
    sun_exposure: "Sol pleno",
    watering: "Abundante, mantendo o solo sempre úmido",
    days_to_germination: "7-10 dias",
    days_to_harvest: "50-70 dias",
    height: "Trepadeira (1-2 metros com suporte)",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Girassol", "Milho", "Feijão"],
  },
  {
    id: "012",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269319/espinafre.jpg",
    name: "Espinafre",
    germination_rate: "80%",
    seed_count: "150",
    origin: "Ásia",
    season: "Outono/Inverno",
    url: "https://example.com/espinafre",
    description:
      "O espinafre é uma hortaliça folhosa de cor verde escura, rica em ferro e vitaminas. Suas folhas podem ser consumidas cruas em saladas ou cozidas em diversos pratos, como sopas, refogados e tortas.",
    planting_depth: "1 cm",
    spacing: "20-30 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "40-50 dias",
    height: "20-30 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Morango", "Couve-flor", "Feijão"],
  },
  {
    id: "013",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269320/cebolinha.jpg",
    name: "Cebolinha",
    germination_rate: "85%",
    seed_count: "200",
    origin: "Ásia",
    season: "Ano todo",
    url: "https://example.com/cebolinha",
    description:
      "A cebolinha é uma erva aromática de folhas cilíndricas, alongadas e ocas, com sabor suave de cebola. Muito utilizada como tempero em diversos pratos, saladas e molhos, sendo geralmente adicionada ao final do preparo.",
    planting_depth: "0.5 cm",
    spacing: "10-15 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "10-14 dias",
    days_to_harvest: "60-90 dias",
    height: "25-35 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Cenoura", "Tomate", "Morango"],
  },
  {
    id: "014",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269321/salsa.jpg",
    name: "Salsa",
    germination_rate: "70%",
    seed_count: "200",
    origin: "Mediterrâneo",
    season: "Ano todo",
    url: "https://example.com/salsa",
    description:
      "A salsa é uma erva aromática de folhas verdes recortadas e sabor característico. Amplamente utilizada como tempero e finalização de pratos na culinária mundial, é rica em vitaminas e minerais.",
    planting_depth: "0.5 cm",
    spacing: "15-20 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "14-21 dias",
    days_to_harvest: "70-90 dias",
    height: "30-40 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Tomate", "Aspargo", "Milho"],
  },
  {
    id: "015",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269322/rabanete.jpg",
    name: "Rabanete",
    germination_rate: "95%",
    seed_count: "150",
    origin: "Ásia",
    season: "Outono/Inverno",
    url: "https://example.com/rabanete",
    description:
      "O rabanete é uma raiz tuberosa de cor vermelha por fora e branca por dentro, com sabor picante e textura crocante. De crescimento rápido, é consumido cru em saladas ou como aperitivo.",
    planting_depth: "1 cm",
    spacing: "5-8 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "3-7 dias",
    days_to_harvest: "20-30 dias",
    height: "15-20 cm (folhagem)",
    soil_type: "Solto, arenoso, bem drenado",
    companion_plants: ["Alface", "Ervilha", "Pepino"],
  },
  {
    id: "016",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269323/couve.jpg",
    name: "Couve",
    germination_rate: "85%",
    seed_count: "100",
    origin: "Europa",
    season: "Outono/Inverno",
    url: "https://example.com/couve",
    description:
      "A couve é uma hortaliça folhosa de cor verde escura, com folhas grandes e textura firme. Rica em vitaminas e minerais, pode ser consumida crua em sucos e saladas ou cozida em refogados e sopas.",
    planting_depth: "1 cm",
    spacing: "40-50 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, evitando encharcamento",
    days_to_germination: "7-10 dias",
    days_to_harvest: "60-80 dias",
    height: "40-60 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Alecrim", "Sálvia", "Tomilho"],
  },
  {
    id: "017",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269324/hortelã.jpg",
    name: "Hortelã",
    germination_rate: "75%",
    seed_count: "200",
    origin: "Europa",
    season: "Primavera/Verão",
    url: "https://example.com/hortela",
    description:
      "A hortelã é uma erva aromática de folhas verdes dentadas e aroma refrescante. Muito utilizada em chás, sucos, sobremesas e pratos salgados, possui propriedades digestivas e refrescantes.",
    planting_depth: "0.5 cm",
    spacing: "20-30 cm",
    sun_exposure: "Meia-sombra",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "10-15 dias",
    days_to_harvest: "60-90 dias",
    height: "30-60 cm",
    soil_type: "Rico em matéria orgânica, úmido",
    companion_plants: ["Tomate", "Repolho", "Brócolis"],
  },
  {
    id: "018",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269325/alecrim.jpg",
    name: "Alecrim",
    germination_rate: "70%",
    seed_count: "100",
    origin: "Mediterrâneo",
    season: "Primavera",
    url: "https://example.com/alecrim",
    description:
      "O alecrim é uma erva aromática de folhas finas, alongadas e aroma intenso. Muito utilizado na culinária mediterrânea para temperar carnes, batatas e pães, também possui propriedades medicinais.",
    planting_depth: "0.5 cm",
    spacing: "30-40 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, deixando secar entre regas",
    days_to_germination: "14-21 dias",
    days_to_harvest: "90-180 dias",
    height: "60-100 cm",
    soil_type: "Arenoso, bem drenado, pobre",
    companion_plants: ["Sálvia", "Tomilho", "Couve"],
  },
  {
    id: "019",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269326/morango.jpg",
    name: "Morango",
    germination_rate: "80%",
    seed_count: "30",
    origin: "América do Norte/Europa",
    season: "Outono/Inverno",
    url: "https://example.com/morango",
    description:
      "O morango é uma fruta pequena, vermelha e suculenta, com sabor doce e levemente ácido. Rico em vitamina C e antioxidantes, é muito apreciado in natura, em sobremesas, sucos e geleias.",
    planting_depth: "0.5 cm",
    spacing: "30-40 cm",
    sun_exposure: "Meia-sombra a sol pleno",
    watering: "Regular, evitando molhar as folhas",
    days_to_germination: "14-28 dias",
    days_to_harvest: "150-180 dias",
    height: "15-30 cm",
    soil_type: "Rico em matéria orgânica, levemente ácido",
    companion_plants: ["Alface", "Espinafre", "Cebolinha"],
  },
  {
    id: "020",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269327/capim-limao.jpg",
    name: "Capim-Limão",
    germination_rate: "75%",
    seed_count: "100",
    origin: "Ásia",
    season: "Primavera/Verão",
    url: "https://example.com/capim-limao",
    description:
      "O capim-limão é uma erva aromática de folhas longas e finas, com aroma cítrico característico. Muito utilizado em chás, infusões e na culinária asiática, possui propriedades calmantes e digestivas.",
    planting_depth: "1 cm",
    spacing: "30-40 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, tolerante a períodos secos",
    days_to_germination: "10-20 dias",
    days_to_harvest: "90-120 dias",
    height: "60-120 cm",
    soil_type: "Bem drenado, moderadamente fértil",
    companion_plants: ["Hortelã", "Manjericão", "Alecrim"],
  },
  {
    id: "021",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269328/milho.jpg",
    name: "Milho",
    germination_rate: "90%",
    seed_count: "50",
    origin: "América Central",
    season: "Primavera/Verão",
    url: "https://example.com/milho",
    description:
      "O milho é um cereal de origem americana, com espigas repletas de grãos dourados e adocicados. Versátil na culinária, pode ser consumido cozido, assado, em forma de farinha ou como ingrediente em diversos pratos.",
    planting_depth: "3-5 cm",
    spacing: "30-40 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, especialmente durante a formação das espigas",
    days_to_germination: "7-10 dias",
    days_to_harvest: "70-100 dias",
    height: "1.5-2.5 metros",
    soil_type: "Fértil, bem drenado, rico em nitrogênio",
    companion_plants: ["Feijão", "Abóbora", "Pepino"],
  },
  {
    id: "022",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269329/feijao.jpg",
    name: "Feijão",
    germination_rate: "85%",
    seed_count: "40",
    origin: "América do Sul",
    season: "Primavera/Verão",
    url: "https://example.com/feijao",
    description:
      "O feijão é uma leguminosa rica em proteínas e fibras, com vagens que contêm sementes comestíveis. Alimento básico na culinária brasileira, possui diversas variedades como carioca, preto e vermelho.",
    planting_depth: "2-3 cm",
    spacing: "10-15 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, evitando encharcamento",
    days_to_germination: "7-14 dias",
    days_to_harvest: "60-90 dias",
    height: "30-60 cm",
    soil_type: "Bem drenado, levemente ácido",
    companion_plants: ["Milho", "Batata", "Cenoura"],
  },
  {
    id: "023",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269330/abobora.jpg",
    name: "Abóbora",
    germination_rate: "90%",
    seed_count: "15",
    origin: "América Central",
    season: "Primavera/Verão",
    url: "https://example.com/abobora",
    description:
      "A abóbora é um fruto rasteiro de casca dura e polpa alaranjada, rica em vitaminas e antioxidantes. Versátil na culinária, pode ser preparada em pratos doces e salgados, sopas, purês e assados.",
    planting_depth: "2-3 cm",
    spacing: "100-150 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-10 dias",
    days_to_harvest: "90-120 dias",
    height: "Rasteira (vines de 3-6 metros)",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Milho", "Feijão", "Manjericão"],
  },
  {
    id: "024",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269331/quiabo.jpg",
    name: "Quiabo",
    germination_rate: "75%",
    seed_count: "50",
    origin: "África",
    season: "Primavera/Verão",
    url: "https://example.com/quiabo",
    description:
      "O quiabo é um fruto verde alongado com textura mucilaginosa característica. Rico em fibras e nutrientes, é muito utilizado na culinária brasileira, africana e do sul dos Estados Unidos em ensopados e refogados.",
    planting_depth: "1-2 cm",
    spacing: "40-50 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "55-65 dias",
    height: "1-2 metros",
    soil_type: "Fértil, bem drenado, rico em matéria orgânica",
    companion_plants: ["Tomate", "Pimentão", "Berinjela"],
  },
  {
    id: "025",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269332/berinjela.jpg",
    name: "Berinjela",
    germination_rate: "80%",
    seed_count: "30",
    origin: "Índia/Ásia",
    season: "Primavera/Verão",
    url: "https://example.com/berinjela",
    description:
      "A berinjela é um fruto de cor roxa escura brilhante e polpa esponjosa. Versátil na culinária, pode ser grelhada, assada, refogada ou utilizada em conservas e patês, sendo rica em antioxidantes.",
    planting_depth: "0.5-1 cm",
    spacing: "50-60 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "70-85 dias",
    height: "60-90 cm",
    soil_type: "Rico em matéria orgânica, bem drenado",
    companion_plants: ["Feijão", "Tomilho", "Manjericão"],
  },
  {
    id: "026",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269333/repolho.jpg",
    name: "Repolho",
    germination_rate: "85%",
    seed_count: "100",
    origin: "Europa",
    season: "Outono/Inverno",
    url: "https://example.com/repolho",
    description:
      "O repolho é uma hortaliça de folhas sobrepostas que formam uma cabeça compacta. Rico em vitaminas e minerais, pode ser consumido cru em saladas, refogado, em sopas ou fermentado como chucrute.",
    planting_depth: "0.5-1 cm",
    spacing: "40-50 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "5-10 dias",
    days_to_harvest: "60-90 dias",
    height: "30-45 cm",
    soil_type: "Fértil, bem drenado, rico em matéria orgânica",
    companion_plants: ["Alface", "Beterraba", "Ervilha"],
  },
  {
    id: "027",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269334/brocolis.jpg",
    name: "Brócolis",
    germination_rate: "90%",
    seed_count: "100",
    origin: "Itália",
    season: "Outono/Inverno",
    url: "https://example.com/brocolis",
    description:
      "O brócolis é uma hortaliça da família das crucíferas, com inflorescências verdes agrupadas em formato de árvore. Rico em vitaminas, minerais e antioxidantes, pode ser consumido cozido, refogado ou em sopas.",
    planting_depth: "0.5-1 cm",
    spacing: "40-50 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "5-10 dias",
    days_to_harvest: "60-80 dias",
    height: "60-90 cm",
    soil_type: "Fértil, bem drenado, rico em matéria orgânica",
    companion_plants: ["Alface", "Cebola", "Camomila"],
  },
  {
    id: "028",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269335/couve-flor.jpg",
    name: "Couve-flor",
    germination_rate: "85%",
    seed_count: "100",
    origin: "Mediterrâneo",
    season: "Outono/Inverno",
    url: "https://example.com/couve-flor",
    description:
      "A couve-flor é uma hortaliça com inflorescência compacta e carnuda, geralmente branca. Rica em vitaminas e minerais, pode ser consumida cozida, refogada, em gratinados ou como substituto de carboidratos em dietas.",
    planting_depth: "0.5-1 cm",
    spacing: "50-60 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "5-10 dias",
    days_to_harvest: "70-90 dias",
    height: "40-60 cm",
    soil_type: "Fértil, bem drenado, rico em matéria orgânica",
    companion_plants: ["Alface", "Cebola", "Ervilha"],
  },
  {
    id: "029",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269336/ervilha.jpg",
    name: "Ervilha",
    germination_rate: "90%",
    seed_count: "50",
    origin: "Oriente Médio",
    season: "Outono/Inverno",
    url: "https://example.com/ervilha",
    description:
      "A ervilha é uma leguminosa de vagens que contêm pequenas sementes verdes e doces. Rica em proteínas e fibras, pode ser consumida fresca, congelada ou seca em diversos pratos como sopas, purês e saladas.",
    planting_depth: "2-3 cm",
    spacing: "5-10 cm",
    sun_exposure: "Sol pleno a meia-sombra",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "60-70 dias",
    height: "60-180 cm (com suporte)",
    soil_type: "Bem drenado, levemente alcalino",
    companion_plants: ["Cenoura", "Rabanete", "Pepino"],
  },
  {
    id: "030",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269337/cebola.jpg",
    name: "Cebola",
    germination_rate: "80%",
    seed_count: "200",
    origin: "Ásia Central",
    season: "Outono/Inverno",
    url: "https://example.com/cebola",
    description:
      "A cebola é um bulbo formado por camadas sobrepostas, com sabor e aroma característicos. Ingrediente básico na culinária mundial, pode ser consumida crua, refogada, assada ou em conservas.",
    planting_depth: "1-2 cm",
    spacing: "10-15 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, reduzindo próximo à colheita",
    days_to_germination: "7-14 dias",
    days_to_harvest: "90-120 dias",
    height: "30-45 cm (folhagem)",
    soil_type: "Bem drenado, arenoso, rico em matéria orgânica",
    companion_plants: ["Cenoura", "Beterraba", "Alface"],
  },
  {
    id: "031",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269338/alho.jpg",
    name: "Alho",
    germination_rate: "85%",
    seed_count: "10 bulbilhos",
    origin: "Ásia Central",
    season: "Outono/Inverno",
    url: "https://example.com/alho",
    description:
      "O alho é um bulbo composto por bulbilhos de sabor e aroma intensos. Amplamente utilizado como tempero na culinária mundial, possui propriedades medicinais e é rico em compostos benéficos à saúde.",
    planting_depth: "2-3 cm",
    spacing: "10-15 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, reduzindo próximo à colheita",
    days_to_germination: "7-14 dias",
    days_to_harvest: "180-210 dias",
    height: "40-60 cm",
    soil_type: "Bem drenado, rico em matéria orgânica",
    companion_plants: ["Cenoura", "Beterraba", "Morango"],
  },
  {
    id: "032",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269339/tomilho.jpg",
    name: "Tomilho",
    germination_rate: "75%",
    seed_count: "200",
    origin: "Mediterrâneo",
    season: "Primavera",
    url: "https://example.com/tomilho",
    description:
      "O tomilho é uma erva aromática de pequenas folhas e aroma intenso. Muito utilizado na culinária mediterrânea para temperar carnes, molhos e sopas, também possui propriedades medicinais e antissépticas.",
    planting_depth: "0.5 cm",
    spacing: "20-30 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, tolerante à seca",
    days_to_germination: "14-21 dias",
    days_to_harvest: "90-180 dias",
    height: "20-30 cm",
    soil_type: "Bem drenado, arenoso, alcalino",
    companion_plants: ["Alecrim", "Sálvia", "Morango"],
  },
  {
    id: "033",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269340/oregano.jpg",
    name: "Orégano",
    germination_rate: "70%",
    seed_count: "200",
    origin: "Mediterrâneo",
    season: "Primavera",
    url: "https://example.com/oregano",
    description:
      "O orégano é uma erva aromática de pequenas folhas e sabor característico. Muito utilizado na culinária italiana e mediterrânea, especialmente em pizzas, molhos de tomate e pratos com queijo.",
    planting_depth: "0.5 cm",
    spacing: "20-30 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, tolerante à seca",
    days_to_germination: "7-14 dias",
    days_to_harvest: "90-180 dias",
    height: "30-50 cm",
    soil_type: "Bem drenado, calcário",
    companion_plants: ["Manjericão", "Tomilho", "Pimentão"],
  },
  {
    id: "034",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269341/salvia.jpg",
    name: "Sálvia",
    germination_rate: "70%",
    seed_count: "100",
    origin: "Mediterrâneo",
    season: "Primavera",
    url: "https://example.com/salvia",
    description:
      "A sálvia é uma erva aromática de folhas aveludadas e aroma intenso. Utilizada na culinária para temperar carnes, molhos e recheios, também possui propriedades medicinais e é apreciada por suas flores ornamentais.",
    planting_depth: "0.5 cm",
    spacing: "30-40 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, tolerante à seca",
    days_to_germination: "14-21 dias",
    days_to_harvest: "75-90 dias",
    height: "40-60 cm",
    soil_type: "Bem drenado, arenoso",
    companion_plants: ["Alecrim", "Tomilho", "Repolho"],
  },
  {
    id: "035",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269342/melancia.jpg",
    name: "Melancia",
    germination_rate: "85%",
    seed_count: "20",
    origin: "África",
    season: "Primavera/Verão",
    url: "https://example.com/melancia",
    description:
      "A melancia é um fruto grande de casca verde e polpa vermelha suculenta e doce. Rica em água e nutrientes, é muito apreciada in natura como sobremesa refrescante, especialmente no verão.",
    planting_depth: "2-3 cm",
    spacing: "150-200 cm",
    sun_exposure: "Sol pleno",
    watering: "Abundante, especialmente durante a formação dos frutos",
    days_to_germination: "7-14 dias",
    days_to_harvest: "80-100 dias",
    height: "Rasteira (vines de 3-5 metros)",
    soil_type: "Arenoso, bem drenado, rico em matéria orgânica",
    companion_plants: ["Milho", "Girassol", "Manjericão"],
  },
  {
    id: "036",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269343/melao.jpg",
    name: "Melão",
    germination_rate: "85%",
    seed_count: "25",
    origin: "África/Ásia",
    season: "Primavera/Verão",
    url: "https://example.com/melao",
    description:
      "O melão é um fruto de casca amarelada e polpa doce e aromática. Rico em vitaminas e minerais, é consumido in natura como sobremesa, em saladas de frutas ou sucos refrescantes.",
    planting_depth: "2-3 cm",
    spacing: "100-150 cm",
    sun_exposure: "Sol pleno",
    watering: "Regular, reduzindo próximo à colheita",
    days_to_germination: "7-14 dias",
    days_to_harvest: "70-90 dias",
    height: "Rasteira (vines de 2-3 metros)",
    soil_type: "Bem drenado, rico em matéria orgânica",
    companion_plants: ["Milho", "Girassol", "Capim-limão"],
  },
  {
    id: "037",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269344/mostarda.jpg",
    name: "Mostarda",
    germination_rate: "90%",
    seed_count: "200",
    origin: "Ásia",
    season: "Outono/Inverno",
    url: "https://example.com/mostarda",
    description:
      "A mostarda é uma hortaliça de folhas verdes com sabor picante característico. Suas folhas podem ser consumidas em saladas, refogados e sopas, enquanto suas sementes são utilizadas para produzir o condimento de mesmo nome.",
    planting_depth: "0.5-1 cm",
    spacing: "15-20 cm",
    sun_exposure: "Sol pleno a meia-sombra",
    watering: "Regular, mantendo o solo úmido",
    days_to_germination: "4-7 dias",
    days_to_harvest: "40-50 dias (folhas)",
    height: "30-60 cm",
    soil_type: "Fértil, bem drenado",
    companion_plants: ["Alface", "Pepino", "Cenoura"],
  },
  {
    id: "038",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269345/agriao.jpg",
    name: "Agrião",
    germination_rate: "85%",
    seed_count: "200",
    origin: "Europa/Ásia",
    season: "Outono/Inverno",
    url: "https://example.com/agriao",
    description:
      "O agrião é uma hortaliça aquática de folhas verde-escuras com sabor levemente picante. Rico em vitaminas e minerais, é consumido cru em saladas, sanduíches, sucos verdes ou levemente refogado.",
    planting_depth: "0.5 cm",
    spacing: "10-15 cm",
    sun_exposure: "Meia-sombra",
    watering: "Abundante, prefere solo constantemente úmido",
    days_to_germination: "7-14 dias",
    days_to_harvest: "40-60 dias",
    height: "15-30 cm",
    soil_type: "Rico em matéria orgânica, constantemente úmido",
    companion_plants: ["Rabanete", "Cebolinha", "Hortelã"],
  },
  {
    id: "039",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269346/calendula.jpg",
    name: "Calêndula",
    germination_rate: "80%",
    seed_count: "50",
    origin: "Mediterrâneo",
    season: "Primavera/Outono",
    url: "https://example.com/calendula",
    description:
      "A calêndula é uma planta medicinal e ornamental de flores alaranjadas vibrantes. Suas pétalas são utilizadas em chás, pomadas medicinais, cosméticos naturais e como corante alimentar em substituição ao açafrão.",
    planting_depth: "0.5-1 cm",
    spacing: "20-30 cm",
    sun_exposure: "Sol pleno a meia-sombra",
    watering: "Moderada, tolerante à seca",
    days_to_germination: "7-14 dias",
    days_to_harvest: "60-80 dias",
    height: "30-60 cm",
    soil_type: "Bem drenado, moderadamente fértil",
    companion_plants: ["Tomate", "Alface", "Repolho"],
  },
  {
    id: "040",
    img: "https://cdn.awsli.com.br/600x450/2195/2195322/produto/156269347/camomila.jpg",
    name: "Camomila",
    germination_rate: "75%",
    seed_count: "300",
    origin: "Europa/Ásia",
    season: "Primavera",
    url: "https://example.com/camomila",
    description:
      "A camomila é uma planta medicinal de pequenas flores brancas com centro amarelo e aroma adocicado. Muito utilizada em chás calmantes e relaxantes, também possui propriedades anti-inflamatórias e digestivas.",
    planting_depth: "Superficial (sementes precisam de luz)",
    spacing: "15-20 cm",
    sun_exposure: "Sol pleno",
    watering: "Moderada, evitando encharcamento",
    days_to_germination: "7-14 dias",
    days_to_harvest: "60-90 dias",
    height: "30-60 cm",
    soil_type: "Bem drenado, arenoso",
    companion_plants: ["Repolho", "Cebola", "Menta"],
  },
];
